"""fastcode.utils — domain-independent utilities (copy-paste test)."""

# Re-export all public names from the original utils module so that
# existing `from fastcode.utils import X` statements continue to work.
from fastcode.utils._compat import (
    calculate_code_complexity,
    clean_docstring,
    compute_file_hash,
    count_tokens,
    ensure_dir,
    extract_code_snippet,
    format_code_block,
    get_file_extension,
    get_language_from_extension,
    get_repo_name_from_url,
    is_supported_file,
    is_text_file,
    load_config,
    merge_dicts,
    normalize_path,
    resolve_config_paths,
    safe_get,
    safe_jsonable,
    setup_logging,
    should_ignore_path,
    truncate_to_tokens,
    utc_now,
)

__all__ = [
    "calculate_code_complexity",
    "clean_docstring",
    "compute_file_hash",
    "count_tokens",
    "ensure_dir",
    "extract_code_snippet",
    "format_code_block",
    "get_file_extension",
    "get_language_from_extension",
    "get_repo_name_from_url",
    "is_supported_file",
    "is_text_file",
    "load_config",
    "merge_dicts",
    "normalize_path",
    "resolve_config_paths",
    "safe_get",
    "safe_jsonable",
    "setup_logging",
    "should_ignore_path",
    "truncate_to_tokens",
    "utc_now",
]
