"""Minimal type stubs for diskcache."""

from typing import Any

class Cache:
    def __init__(self, directory: str, **kwargs: Any) -> None: ...
    def get(self, key: str, default: Any = ..., read: bool = ..., expire_time: bool = ..., tag: bool = ...) -> Any: ...
    def set(self, key: str, value: Any, expire: int | None = ..., read: bool = ..., tag: str | None = ..., retry: bool = ...) -> bool: ...
    def delete(self, key: str, retry: bool = ...) -> bool: ...
    def clear(self) -> int: ...
    def volume(self) -> int: ...
    @property
    def directory(self) -> str: ...
