"""Minimal type stubs for faiss-cpu."""

from typing import Any

import numpy as np
from numpy.typing import NDArray

METRIC_INNER_PRODUCT: int
METRIC_L2: int

class IndexFlatIP:
    def __init__(self, d: int) -> None: ...
    def add(self, x: NDArray[np.float32]) -> None: ...
    def search(
        self, x: NDArray[np.float32], k: int
    ) -> tuple[NDArray[np.float32], NDArray[np.int64]]: ...
    def reconstruct(self, key: int) -> NDArray[np.float32]: ...
    @property
    def ntotal(self) -> int: ...

class IndexFlatL2:
    def __init__(self, d: int) -> None: ...
    def add(self, x: NDArray[np.float32]) -> None: ...
    def search(
        self, x: NDArray[np.float32], k: int
    ) -> tuple[NDArray[np.float32], NDArray[np.int64]]: ...
    def reconstruct(self, key: int) -> NDArray[np.float32]: ...
    @property
    def ntotal(self) -> int: ...

class _HNSWState:
    efConstruction: int
    efSearch: int

class IndexHNSWFlat:
    hnsw: _HNSWState
    def __init__(self, d: int, M: int, metric: int = ...) -> None: ...
    def add(self, x: NDArray[np.float32]) -> None: ...
    def search(
        self, x: NDArray[np.float32], k: int
    ) -> tuple[NDArray[np.float32], NDArray[np.int64]]: ...
    def reconstruct(self, key: int) -> NDArray[np.float32]: ...
    @property
    def ntotal(self) -> int: ...

class IndexIDMap:
    def __init__(self, index: Any) -> None: ...
    def add_with_ids(self, x: NDArray[np.float32], ids: NDArray[np.int64]) -> None: ...
    def search(
        self, x: NDArray[np.float32], k: int
    ) -> tuple[NDArray[np.float32], NDArray[np.int64]]: ...
    @property
    def ntotal(self) -> int: ...

def normalize_L2(x: NDArray[np.float32]) -> None: ...
def write_index(index: Any, fname: str) -> None: ...
def read_index(fname: str) -> Any: ...
