"""Minimal type stubs for rank_bm25."""

from typing import Any

class BM25Okapi:
    def __init__(self, corpus: list[list[str]], **kwargs: Any) -> None: ...
    def get_scores(self, query: list[str]) -> Any: ...
    def get_top_n(self, query: list[str], documents: list[Any], n: int = ...) -> list[Any]: ...
