"""Minimal type stubs for redis."""

from typing import Any

class Redis:
    def __init__(self, host: str = ..., port: int = ..., db: int = ..., password: str | None = ..., url: str = ..., **kwargs: Any) -> None: ...
    def get(self, name: str | bytes) -> bytes | None: ...
    def set(self, name: str | bytes, value: bytes | str | int, ex: int | None = ..., px: int | None = ..., nx: bool = ..., xx: bool = ...) -> bool | None: ...
    def setex(self, name: str, time: int, value: bytes | str) -> bool: ...
    def delete(self, *names: str | bytes) -> int: ...
    def flushdb(self) -> bool: ...
    def dbsize(self) -> int: ...
    def info(self, section: str | None = ...) -> dict[str, Any]: ...
    def exists(self, *names: str | bytes) -> int: ...
    def expire(self, name: str | bytes, time: int) -> bool: ...
